[package]
name = "rcstruct"
version = "0.1.0"
description = "Generate transparent `Struct(Rc<RefCell<Struct>>)` newtypes"
authors = ["Felix Rabe <felix@rabe.io>"]
edition = "2018"
repository = "https://github.com/felixrabe/rcstruct"

[dependencies]
